project:
  type: website
  output-dir: docs
website:
  title: "presentation-regression-diagnostics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: regression_diagnostics.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



